#!/bin/sh

# Mount /proc
[ -f /proc/cmdline ] || /bin/mount /proc

# Mount for read and write
/bin/mount -o remount,rw  /

# Create /dev/pts directory for pseudo-terminal devices
mkdir -p /dev/pts
mkdir /dev/shm
# Mount system devices from /etc/fstab.
/bin/mount -a

/sbin/mdev -s

#
# Network interfaces
#

# Set lo
ifconfig lo 127.0.0.1

# Turn on logging
/sbin/syslogd

#
HOSTNAME=snacklinux
hostname $HOSTNAME


echo
echo "--------------------------------------------------------------"
echo "Welcome to $HOSTNAME!"
echo
echo "Kernel release: `uname -s` `uname -r`"
echo "Kernel version: `uname -v`"
echo
echo "--------------------------------------------------------------"
echo
